version: '3'
services:
  j2e_premium_polyevent:
    image: lucassalut/j2e_premium_polyevent
    ports:
     - "8080:8080"
    environment:
      - AgendaAddr=mono-polyevent
      - AgendaPort=9090

  mono-polyevent:
    image: lucassalut/mono_polyevent
    ports:
     - "9090:9090"
