package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-03-22T04:12:31.829-04:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "EventServiceService", 
                  wsdlLocation = "file:/home/osboxes/si4/semester_2/isadevops/main/j2e/webapp/src/main/resources/EventService.wsdl",
                  targetNamespace = "http://webservice/") 
public class EventServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice/", "EventServiceService");
    public final static QName EventServicePort = new QName("http://webservice/", "EventServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/osboxes/si4/semester_2/isadevops/main/j2e/webapp/src/main/resources/EventService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EventServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/osboxes/si4/semester_2/isadevops/main/j2e/webapp/src/main/resources/EventService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EventServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EventServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EventServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EventServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EventServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EventServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IEventService
     */
    @WebEndpoint(name = "EventServicePort")
    public IEventService getEventServicePort() {
        return super.getPort(EventServicePort, IEventService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEventService
     */
    @WebEndpoint(name = "EventServicePort")
    public IEventService getEventServicePort(WebServiceFeature... features) {
        return super.getPort(EventServicePort, IEventService.class, features);
    }

}
