package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-03-22T04:12:31.752-04:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://webservice/", name = "IEventService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEventService {

    @WebMethod
    @RequestWrapper(localName = "createEvent", targetNamespace = "http://webservice/", className = "webservice.CreateEvent")
    @ResponseWrapper(localName = "createEventResponse", targetNamespace = "http://webservice/", className = "webservice.CreateEventResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String createEvent(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
